### ISSUE TITLE
Make Event abstract class unit tests more like real world use case

### ISSUE THREAD

**Issue by Cooryd** [libero/event-bus#18]
In our `event.test.ts` tests we are using a factory function to create an Event object like this:
https://github.com/libero/event-bus/blob/ad1bb6acd4eac75736e7328695b3a10feda491d8/src/event-bus/event.test.ts#L4

This is a work around typescripts insistence that an abstract class should not be directly instantiated and should only be extended. While the tests do add code coverage, they aren't testing realistic usage of the abstract class. We should test based on the following expected way of using the abstract class:

```
export class UserLoggedInEvent extends Event {
    constructor(payload: UserLoggedInPayload) {
        super(LiberoEventType.userLoggedInIdentifier, payload);
    }
}
```

**Comment by diversemix** [comment]
Cloned into reviewer
